sudo: false
language: android
jdk: oraclejdk8

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
 
 env:
  global:
       - ANDROID_API_LEVEL=25
       - EMULATOR_API_LEVEL=21
       - ANDROID_BUILD_TOOLS_VERSION=25.0.2
       - ANDROID_ABI=google_apis/armeabi-v7a
       - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
       

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    # Google Play Services
    - extra-google-google_play_services
    # Support library
    - extra-android-support
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - addon-google_apis-google-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
     
before_script:
- sdkmanager --list
  - echo no | android create avd --force -n test -k 'system-images;android-25;google_apis;x86'
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
script:
script:
  # other script steps might be done before running the actual analysis
        - sonar-scanner
        - ./gradlew sonarqube  -Dsonar.projectKey=ChristianTaidi_CS_G1 -Dsonar.organization=christiantaidi-github -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login="Christianaidi"
        - ./gradlew clean
        - ./gradlew assembleDebug
        - ./gradlew assembleDebugAndroidTest
    #    - travis encrypt --com "GITHUB_TOKEN=abd13ad1ec5e145780ae7a4208beafc5eb3f9aa3" --add
        
before_install:
          - mkdir "$ANDROID_HOME/licenses" || true
          - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
          - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
          - chmod 777 -R /home/travis/*
          - chmod +x gradlew
          - yes | sdkmanager --update
          - sudo apt-get install travis
      

          
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "app/**"
  skip_cleanup: true
  on:
    tags: false
    
addons:
  sonarcloud:
    organization: "christiantaidi-github" # the key of the org you chose at step #3
    token:
      secure :"cRA/ph0naht9i5YlnWGtd7zPXtDLUObS8Q9VIU9CLZKhy+MXlEl2eagHcTSrxXn6snLsYTW2ctsqPifMekY+RpyMq0YHoq2a2Uz/U/2Ttp2+vZ1wPqokhYPrOXQcASoVnaU5Mu9RNxDKKThnJbPN/Iz52RJx0z/e/ocrTgX8kne8sUeJqufAV3J6UMFFhEJgJyak64op80vl1BkkhCO8UKkp+uIv5Zd8cMQzO8WFdgaFX+VSY/NOt0g5jiT6vyNYP4jtwf8FRr9FFlL2gWU1Wc8UfL6lO73Ci7HnQPweQh/Swds21NW/kvyX/p5OFnKiE2xA5I0qjxfZGt8nz4w/k7nqkifBip1+R8n/A8hqGMtespkZww32b/CYz/UGss/dnJQ+8M5HWnNdYmiIEvfrPcJWFG/bEspyTv2CH3X/rZPBaTrm12lsEIjzwFzT7N98NkZ8eAYTxZpox5WYMJbMJNsMrTesk7w2wUBuiqVQE7efgHvWoZHnMw+6i15EexjnuHf7XEeGSiWvosObggykCEX0yAhpL7oodak1E2a0uImDMrSxlG3JG5JZlpIJH43lXFoaJkfY+2aVw9nXXzRw3rsAr3GhivmsM0DaxhfZ9LffQdaHBu+SL+GjtNXw12bdSS1yW1ZFJkmA8eiUmj95vXwS60rOi/0mEi/5xhzsvhM="    

           
